env_to_dotenv:
	@echo FORMX_EXTRACTOR_ID=$(FORMX_EXTRACTOR_ID) >> .env
	@echo FORMX_ACCESS_TOKEN=${FORMX_ACCESS_TOKEN} >> .env
	@echo FORMX_API_HOST=${FORMX_API_HOST} >> .env
	@echo "Generated .env from current environment"
